name: Convert Docker Images to WASM and Deploy to GitHub Pages

on:
  push:
    paths:
      - 'Container_Library/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  convert_to_wasm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install container2wasm
        run: |
          wget https://github.com/ktock/container2wasm/releases/download/v0.6.4/container2wasm-v0.6.4-linux-amd64.tar.gz
          tar -xzvf container2wasm-v0.6.4-linux-amd64.tar.gz
          sudo mv c2w /usr/local/bin/
          sudo mv c2w-net /usr/local/bin/

      - name: Convert Docker Images to WASM
        run: |
          mkdir -p docs
          for dir in Container_Library/*; do
            [ -d "$dir" ] || continue
            NAME=$(basename "$dir")
            for ARCH in amd64 riscv64 aarch64; do
              OUTPUT_FILE="docs/${ARCH}-${NAME}-wasi.wasm"
              if [ -f "$dir/Dockerfile" ]; then
                docker buildx build -t "$NAME" "$dir" --platform=linux/${ARCH}
                c2w --target-arch="$ARCH" "$NAME" "$OUTPUT_FILE"
              elif [ -f "$dir/image" ]; then
                IMAGE=$(cat "$dir/image")
                docker pull "$IMAGE"
                c2w --target-arch="$ARCH" "$IMAGE" "$OUTPUT_FILE"
              fi
            done
          done

      - name: Upload WASM Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasm-artifacts
          path: docs/*.wasm

      - name: Generate GitHub Pages HTML
        run: |
          echo '<html><head><title>WASM Containers</title></head><body><h1>Available WASM Containers</h1><ul>' > docs/index.html
          for file in docs/*.wasm; do
            [ -f "$file" ] || continue
            FILENAME=$(basename "$file")
            echo "<li><a href='${FILENAME}'>${FILENAME}</a></li>" >> docs/index.html
          done
          echo '</ul></body></html>' >> docs/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
